// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Quobject.SocketIoClientDotNet.Client;

namespace WebSocketDemo.Touch
{
	public partial class MainViewController : UIViewController
	{
		private Socket socket;

		public MainViewController (IntPtr handle) : base (handle)
		{
//			System.Net.WebRequest.DefaultWebProxy = null;
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			bSend.TouchUpInside += (object sender, EventArgs e) => {
				var message = tfMessage.Text;
				socket.Emit("message", message);
			};

			socket = IO.Socket(Constants.HOST);
			socket.On ("message", (message) => {
				InvokeOnMainThread(() => {
					var alert = new UIAlertView("From server:", message.ToString(), null, "OK", null);
					alert.Show();
				});
			});
		}
	}
}
